# configurated cron, so that the script is invoked every day at 16.00 pm
name: NBP Pipeline Cron

on: 
  schedule:
    - cron: "0 16 * * 1-5" # Monday to Friday at 16
  workflow_dispatch: # lets it be invoked manually with a button in GitHub

permissions:
  contents: write # bot can do the git push

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Pipeline
      env:
        # secrets mapping
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py --currencies USD,EUR --check-gold --days 30
    - name: Commit artifacts (Database & Charts)
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/database/*.duckdb data/reports/*.png data/pipeline.log
        git commit -m "Auto-update database and charts $(date)" || echo "No changes"
        git push 